import {StyleSheet} from "react-native";
import {Spacing} from "@assets";
import {Colors, FontSize, FontWithBold_Barlow, Shadow} from "@theme";

export const styles=StyleSheet.create({
    container:{
        marginHorizontal:Spacing.width16
    },
    viewRow:{
        flexDirection:'row',
        alignItems:'flex-end',
        justifyContent:'space-between',
        marginBottom:Spacing.height16
    },
    title:{
        fontSize:FontSize.Font18,
        ...FontWithBold_Barlow.Bold_Barlow_700,
        color:Colors.black
    },
    des:{
        fontSize:FontSize.Font12,
        ...FontWithBold_Barlow.Bold_Barlow_600,
        textDecorationLine:'underline',
        color:Colors.colorMain

    },
    viewCategory:{
        margin:Spacing.width8,
        alignItems:'center',
    },
    img:{
        width:Spacing.width50,
        height:Spacing.width50,
    },
    viewImg:{
        padding:8,
        backgroundColor:Colors.white,
        ...Shadow.normal,
        borderRadius:8

    },
    txt:{
        fontSize:FontSize.Font14,
        ...FontWithBold_Barlow.Medium_Barlow_400,
        color:Colors.black,
        width:Spacing.width60,
        marginTop:8,
        textAlign:'center'
    },
    viewProduct:{
        backgroundColor:Colors.white,
        ...Shadow.normal,
        marginRight:Spacing.width16,
        marginVertical:Spacing.width8,
        width:Spacing.width150,
        height:Spacing.height200,
        borderRadius:Spacing.width8
    },
    img_product:{
        width:Spacing.width150,
        height:Spacing.height100
    },
    txt_product:{
        fontSize:FontSize.Font14,
        ...FontWithBold_Barlow.Bold_Barlow_600,
        color:Colors.black,
        width:Spacing.width150-Spacing.width16,
        marginTop:8,
        marginHorizontal:Spacing.width8,

    },
    txt_price_product:{
        fontSize:FontSize.Font16,
        ...FontWithBold_Barlow.Bold_Barlow_700,
        color:Colors.black,
    },
    viewPrice:{
        position:"absolute",
        bottom:10,
        marginHorizontal:Spacing.width8,
        flexDirection:'row',
        alignItems:'flex-end',
        justifyContent:'space-between',
        width:Spacing.width150-Spacing.width16,
    },
    txt_sold_product:{
        fontSize:FontSize.Font10,
        ...FontWithBold_Barlow.Medium_Barlow_400,
        color:Colors.black,
    },
})
